options:
  drupal-version:
    type: string
    default: "7"
    description: "Drupal version, currently supported 6 and 7."
  drush-version:
    type: string
    default: "6.x"
    description: "Drush version to be installed."
  drupal-profile:
    type: string
    default: "standard"
    description: "Profile name like standard, minimal or testing."
  drupal-site-name:
    type: string
    default: "Your fresh new site"
    description: "The Site Name, used when is a fresh install."
  drupal-admin-username:
    type: string
    default: "admin"
    description: "The default administrator user name."
  drupal-admin-email:
    type: string
    default: "admin@localhost.com"
    description: "The default administrator user name."
  drupal-admin-password:
    type: string
    default: ""
    description: "The default administrator password."
  install-compass:
    type: boolean
    default: true
    description: "Install SASS/Compass, so that means ruby and rubygems will be installed."
  drupal-source:
    type: string
    default: "drush"
    description: >
      From where the Drupal will be downloaded, currently supported a repository Git (Ex. git@host:path/repo.git) or 'drush' to download from the Drupal.org.
      Deploying from Git a Lullabot boilerplate based fork is expected https://github.com/TallerWebSolutions/drupal-boilerplate
  deploy-key:
    type: string
    default: ""
    description: "A deploy ssh key that is stored on the server and grants access to a Git repository, for example."
  drupal-db-dump:
    type: string
    default: ""
    description: >
      Database dump file to import when installing Drupal from a Git repository, currently only raw (.sql) or compressed with gzip (.gz).
      Example: "/var/www/databases/dev-dump.sql" or "http://old-url.com/sites/default/files/backup-dump.sql.gz".
  # install-drupal-boilerplate:
  #   type: boolean
  #   default: true
  #   description: "Use boilerplate."
  # drupal-boilerplate-destination:
  #   type: string
  #   default: "/var/www"
  #   description: "Destination path of the boilerplate."
  drupal-boilerplate-source:
    type: string
    default: "https://github.com/TallerWebSolutions/drupal-boilerplate.git"
    description: "Git repository of the boilerplate to install in case it's a new project from scratch."
  drupal-path:
    type: string
    default: "/var/www/docroot"
    description: >
      In case you have an existant Drupal that hasn't use a boilerplate, you can always change this to /var/www for example.

